name: Publishing to GitHub Packages (scheduler)

on:
  schedule:
    - cron: '30 19 * * *'
  workflow_dispatch:
    inputs:
      tag:
        description: 'Type of publish'
        type: choice
        options:
          - daily
          - release
        default: 'daily'
        required: true
      branch:
        description: 'Branch to publish from'
        type: string
        default: '25_2'
        required: true

jobs:
  publish:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    name: Run Packages Publishing workflow
    steps:
      - name: Get sources
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            README.md
          sparse-checkout-cone-mode: false

      - name: Trigger Packages Publishing
        run: |
          gh workflow run packages_publishing.yml \
            -f tag=${{ github.event.inputs.tag || 'daily' }} \
            -f filter='' \
            --ref ${{ github.event.inputs.branch || '25_2' }}